import { SpriteDefinition } from '../../ascii/types';

const SN = '#ffffff'; // Sunlit Alpine Snow Peak
const IC = '#e0f2fe'; // Glacial Ice / Powder
const BL = '#60a5fa'; // Atmospheric Mountain Blue Midtone
const DK = '#312e81'; // Deep Indigo Rock Shadow
const NV = '#1e1b4b'; // Deep Crevasse Navy
const BS = '#cbd5e1'; // Glacial Scree / Moraine Base

export const AlpinePeakSprite: SpriteDefinition = {
  id: 'alpine_peak',
  name: 'Glacial Alpine Peak',
  category: 'LANDMARK',
  defaultColor: '#e0f2fe',
  worldWidth: 320,
  worldHeight: 450,
  visualScale: 1.2,
  variants: {
    close: {
      width: 28,
      height: 18,
      anchorX: 14,
      anchorY: 17,
      lines: [
        "             /\\             ",
        "            /░░\\            ",
        "           /░░░░\\           ",
        "          /░░░░░░\\          ",
        "         /░░░/\\░░░\\         ",
        "        /░░░/  \\░░░\\        ",
        "       /░░░/▓▓▓▓\\░░░\\       ",
        "      /░░░/▓▓▓▓▓▓\\░░░\\      ",
        "     /░░░/▓▓▓/\\▓▓▓\\░░░\\     ",
        "    /░░░/▓▓▓/  \\▓▓▓\\░░░\\    ",
        "   /░░░/▓▓▓/▓▓▓▓\\▓▓▓\\░░░\\   ",
        "  /░░░/▓▓▓/▓▓▓▓▓▓\\▓▓▓\\░░░\\  ",
        " /░░░/▓▓▓/▓▓▓/\\▓▓▓\\▓▓▓\\░░░\\ ",
        "/░░░/▓▓▓/▓▓▓/  \\▓▓▓\\▓▓▓\\░░░\\",
        "|░░░|▓▓▓|▓▓▓|▓▓▓|▓▓▓|▓▓▓|░░|",
        "|▒▒▒|▒▒▒|▒▒▒|▒▒▒|▒▒▒|▒▒▒|▒▒|",
        "/==========================\\",
        "::..::..::..::..::..::..::..",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', '', '', '', '', '', SN, SN, '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', '', SN, IC, IC, SN, '', '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', SN, IC, IC, IC, IC, SN, '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', SN, IC, IC, IC, IC, IC, IC, SN, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', SN, IC, IC, IC, DK, DK, IC, IC, IC, SN, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', SN, IC, IC, IC, DK, DK, DK, DK, IC, IC, IC, SN, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', SN, IC, IC, IC, DK, NV, NV, NV, NV, DK, IC, IC, IC, SN, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', SN, IC, IC, IC, DK, NV, NV, NV, NV, NV, NV, DK, IC, IC, IC, SN, '', '', '', '', '', ''],
        ['', '', '', '', '', SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN, '', '', '', '', ''],
        ['', '', '', '', SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN, '', '', '', ''],
        ['', '', '', SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN, '', '', ''],
        ['', '', SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN, '', ''],
        ['', SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, NV, NV, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN, ''],
        [SN, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, NV, NV, NV, NV, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, SN],
        [IC, IC, IC, IC, DK, NV, NV, NV, DK, DK, DK, DK, NV, NV, NV, NV, DK, DK, DK, DK, NV, NV, NV, DK, IC, IC, IC, IC],
        [BL, BL, BL, BL, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, BL, BL, BL, BL],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 19,
      height: 12,
      anchorX: 9,
      anchorY: 11,
      lines: [
        "        /\\         ",
        "       /░░\\        ",
        "      /░░░░\\       ",
        "     /░░/\\░░\\      ",
        "    /░░/▓▓\\░░\\     ",
        "   /░░/▓▓▓▓\\░░\\    ",
        "  /░░/▓▓/\\▓▓\\░░\\   ",
        " /░░/▓▓/▓▓\\▓▓\\░░\\  ",
        "/░░/▓▓/▓▓▓▓\\▓▓\\░░\\ ",
        "|░░|▓▓|▓▓▓▓|▓▓|░░| ",
        "/================\\ ",
        "::..::..::..::..::.",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', SN, SN, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', SN, IC, IC, SN, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', SN, IC, IC, IC, IC, SN, '', '', '', '', '', '', ''],
        ['', '', '', '', '', SN, IC, IC, DK, DK, IC, IC, SN, '', '', '', '', '', ''],
        ['', '', '', '', SN, IC, IC, DK, NV, NV, DK, IC, IC, SN, '', '', '', '', ''],
        ['', '', '', SN, IC, IC, DK, NV, NV, NV, NV, DK, IC, IC, SN, '', '', '', ''],
        ['', '', SN, IC, IC, DK, NV, NV, DK, DK, NV, NV, DK, IC, IC, SN, '', '', ''],
        ['', SN, IC, IC, DK, NV, NV, DK, DK, DK, DK, NV, NV, DK, IC, IC, SN, '', ''],
        [SN, IC, IC, DK, NV, NV, DK, DK, DK, DK, DK, DK, NV, NV, DK, IC, IC, SN, ''],
        [IC, IC, IC, DK, NV, NV, DK, DK, DK, DK, DK, DK, NV, NV, DK, IC, IC, IC, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 12,
      height: 7,
      anchorX: 6,
      anchorY: 6,
      lines: [
        "     /\\     ",
        "    /░░\\    ",
        "   /░/\\░\\   ",
        "  /░/▓▓\\░\\  ",
        " /░/▓▓▓▓\\░\\ ",
        "/==========\\",
        "::..::..::..",
      ],
      colors: [
        ['', '', '', '', '', SN, SN, '', '', '', '', ''],
        ['', '', '', '', SN, IC, IC, SN, '', '', '', ''],
        ['', '', '', SN, IC, DK, DK, IC, SN, '', '', ''],
        ['', '', SN, IC, DK, NV, NV, DK, IC, SN, '', ''],
        ['', SN, IC, DK, NV, NV, NV, NV, DK, IC, SN, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 6,
      height: 4,
      anchorX: 3,
      anchorY: 3,
      lines: [
        "  /\\  ",
        " /░░\\ ",
        "/░/▓\\░",
        "/====\\",
      ],
      colors: [
        ['', '', SN, SN, '', ''],
        ['', SN, IC, IC, SN, ''],
        [SN, IC, DK, NV, DK, IC],
        [BS, BS, BS, BS, BS, BS],
      ],
    },
  },
};
