import { SpriteDefinition } from '../../ascii/types';

const SH = '#4c0519'; // Deep Burgundy Shadow Face
const TC = '#9a3412'; // Terracotta Midtone
const OC = '#d97706'; // Desert Ochre Strata
const HL = '#fde047'; // Sunlit Canyon Highlight
const BS = '#78350f'; // Scree Base

export const CanyonButteSprite: SpriteDefinition = {
  id: 'canyon_butte',
  name: 'Eroded Canyon Butte',
  category: 'LANDMARK',
  defaultColor: '#d97706',
  worldWidth: 180,
  worldHeight: 320,
  visualScale: 1.05,
  variants: {
    close: {
      width: 20,
      height: 18,
      anchorX: 10,
      anchorY: 17,
      lines: [
        "       .---.        ",
        "      /░░░░░\\       ",
        "     |▒▒▒▒▒▒▒|      ",
        "     |▓▓▓▓▓▓▓|      ",
        "    /░░░░░░░░░\\     ",
        "   /▒▒▒▒▒▒▒▒▒▒▒\\    ",
        "   |▓▓▓▓| |▓▓▓▓|    ",
        "   |░░░░░░░░░░░|    ",
        "  /▒▒▒▒▒▒▒▒▒▒▒▒▒\\   ",
        " /▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\\  ",
        " |░░░░|   |░░░░░░|  ",
        " |▒▒▒▒|___|▒▒▒▒▒▒|  ",
        " |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓|  ",
        "/░░░░░░░░░░░░░░░░░\\ ",
        "|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| ",
        "|▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| ",
        "/=================\\ ",
        "::..::..::..::..::..",
      ],
      colors: [
        ['', '', '', '', '', '', '', HL, HL, HL, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', OC, OC, OC, OC, OC, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', TC, TC, TC, TC, TC, TC, TC, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', SH, SH, SH, SH, SH, SH, SH, '', '', '', '', '', '', '', ''],
        ['', '', '', '', OC, OC, OC, OC, OC, OC, OC, OC, OC, '', '', '', '', '', '', ''],
        ['', '', '', TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', '', '', '', '', ''],
        ['', '', '', SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', '', '', '', '', ''],
        ['', '', '', HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, '', '', '', '', '', ''],
        ['', '', OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', '', '', '', ''],
        ['', SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', '', '', ''],
        ['', TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', '', '', ''],
        ['', OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', '', '', ''],
        ['', SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', '', '', ''],
        [OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, ''],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 14,
      height: 12,
      anchorX: 7,
      anchorY: 11,
      lines: [
        "     .--.     ",
        "    /░░░░\\    ",
        "   |▒▒▒▒▒▒|   ",
        "   |▓▓▓▓▓▓|   ",
        "  /░░░░░░░░\\  ",
        " /▒▒▒▒▒▒▒▒▒▒\\ ",
        " |▓▓▓|  |▓▓▓| ",
        " |░░░░░░░░░░| ",
        "/▓▓▓▓▓▓▓▓▓▓▓▓\\",
        "|▒▒▒▒▒▒▒▒▒▒▒▒|",
        "/============\\",
        "::..::..::..::",
      ],
      colors: [
        ['', '', '', '', '', HL, HL, HL, HL, '', '', '', '', ''],
        ['', '', '', '', OC, OC, OC, OC, OC, OC, '', '', '', ''],
        ['', '', '', TC, TC, TC, TC, TC, TC, TC, TC, '', '', ''],
        ['', '', '', SH, SH, SH, SH, SH, SH, SH, SH, '', '', ''],
        ['', '', OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', ''],
        ['', TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, ''],
        ['', SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, ''],
        ['', HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 9,
      height: 8,
      anchorX: 4,
      anchorY: 7,
      lines: [
        "   .-.   ",
        "  /░░░\\  ",
        " |▒▒▒▒▒| ",
        " /░░░░░\\ ",
        " |▓▓▓▓▓| ",
        "/▓▓▓▓▓▓▓\\",
        "/=======\\",
        "::..::..:",
      ],
      colors: [
        ['', '', '', HL, HL, HL, '', '', ''],
        ['', '', OC, OC, OC, OC, OC, '', ''],
        ['', TC, TC, TC, TC, TC, TC, TC, ''],
        ['', OC, OC, OC, OC, OC, OC, OC, ''],
        ['', SH, SH, SH, SH, SH, SH, SH, ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 5,
      height: 4,
      anchorX: 2,
      anchorY: 3,
      lines: [
        " .-. ",
        "/░░░\\",
        "|▓▓▓|",
        "/===\\",
      ],
      colors: [
        ['', HL, HL, HL, ''],
        [OC, OC, OC, OC, OC],
        [SH, SH, SH, SH, SH],
        [BS, BS, BS, BS, BS],
      ],
    },
  },
};
