import { SpriteDefinition } from '../../ascii/types';

const SH = '#4c0519'; // Deep Burgundy Erosion Shadow
const TC = '#9a3412'; // Terracotta Sandstone Midtone
const OC = '#d97706'; // Warm Desert Ochre Strata
const HL = '#fde047'; // Sunlit Canyon Ridge Highlight
const SK = '#65a30d'; // Scrub Flora / Desert Moss
const BS = '#78350f'; // Desert Floor Scree Debris

export const CanyonMesaSprite: SpriteDefinition = {
  id: 'canyon_mesa',
  name: 'Sunbaked Canyon Mesa',
  category: 'LANDMARK',
  defaultColor: '#d97706',
  worldWidth: 260,
  worldHeight: 280,
  visualScale: 1.1,
  variants: {
    close: {
      width: 28,
      height: 16,
      anchorX: 14,
      anchorY: 15,
      lines: [
        "      .Y.       .Y.         ",
        "  .---' '-------' '----.    ",
        " /░░░░░░░░░░░░░░░░░░░░░░\\   ",
        "/▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\\  ",
        "\\▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓/  ",
        " /░░░░░░░░░░░░░░░░░░░░░░\\   ",
        "/▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\\  ",
        "|▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓|  ",
        "\\░░░░░░░░░░░░░░░░░░░░░░░░/  ",
        " /▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\\   ",
        "/▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\\  ",
        "|░░░░░░░░░░░░░░░░░░░░░░░░|  ",
        "/▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\\  ",
        "|▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓|  ",
        "/========================\\  ",
        "::..::..::..::..::..::..::..",
      ],
      colors: [
        ['', '', '', '', '', '', SK, SK, SK, '', '', '', '', '', '', SK, SK, SK, '', '', '', '', '', '', '', '', '', ''],
        ['', '', HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, '', '', '', ''],
        ['', OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', '', ''],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', ''],
        ['', OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', '', ''],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', ''],
        [HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, '', ''],
        ['', TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', '', ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', ''],
        [OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, '', ''],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, '', ''],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 19,
      height: 11,
      anchorX: 9,
      anchorY: 10,
      lines: [
        "    .Y.       .Y.  ",
        " .--' '-------' '--",
        "/░░░░░░░░░░░░░░░░░\\",
        "/▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\\",
        "\\▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓/",
        "/░░░░░░░░░░░░░░░░░\\",
        "|▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓|",
        "\\▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒/",
        "|▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓|",
        "/=================\\",
        "::..::..::..::..::.",
      ],
      colors: [
        ['', '', '', '', SK, SK, SK, '', '', '', '', '', '', SK, SK, SK, '', '', ''],
        ['', HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, ''],
        [OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 13,
      height: 7,
      anchorX: 6,
      anchorY: 6,
      lines: [
        " .--.---.---.",
        "/░░░░░░░░░░░\\",
        "/▒▒▒▒▒▒▒▒▒▒▒\\",
        "\\▓▓▓▓▓▓▓▓▓▓▓/",
        "/░░░░░░░░░░░\\",
        "/===========\\",
        "::..::..::..:",
      ],
      colors: [
        ['', HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, ''],
        [OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC, OC],
        [TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC, TC],
        [SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH, SH],
        [HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL, HL],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 7,
      height: 4,
      anchorX: 3,
      anchorY: 3,
      lines: [
        " .----.",
        "/░░░░░\\",
        "\\▓▓▓▓▓/",
        "/=====\\",
      ],
      colors: [
        ['', HL, HL, HL, HL, HL, ''],
        [OC, OC, OC, OC, OC, OC, OC],
        [SH, SH, SH, SH, SH, SH, SH],
        [BS, BS, BS, BS, BS, BS, BS],
      ],
    },
  },
};
