import { SpriteDefinition } from '../../ascii/types';

const CY = '#06b6d4'; // Cyan Window Arrays
const MG = '#ec4899'; // Magenta Accent Lines
const NV = '#090d16'; // Midnight Facade
const DK = '#1e1b4b'; // Shadow Indigo
const BS = '#020617'; // Cyber Grid Foundation

export const CyberGridBuildingSprite: SpriteDefinition = {
  id: 'scenery_cyber_grid_building',
  name: 'Cyber Stepped Corporate Building',
  category: 'BUILDING',
  defaultColor: '#06b6d4',
  worldWidth: 200,
  worldHeight: 340,
  visualScale: 1.05,
  variants: {
    close: {
      width: 22,
      height: 15,
      anchorX: 11,
      anchorY: 14,
      lines: [
        "      .--------.      ",
        "     .|========|.     ",
        "    |  |[::][::]|  |  ",
        "    |==|========|==|  ",
        "   .|  |[::][::]|  |. ",
        "  |  | |[::][::]| |  |",
        "  |==| |========| |==|",
        "  |  | |[::][::]| |  |",
        " .|==| |========| |==|",
        " | | | |[::][::]| | | ",
        " | |=| |========| |=| ",
        " | | | |[::][::]| | | ",
        " | |===[========]===| ",
        " |_____|________|___| ",
        "::..::..::..::..::..::",
      ],
      colors: [
        ['', '', '', '', '', '', NV, NV, NV, NV, NV, NV, NV, NV, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', NV, MG, MG, MG, MG, MG, MG, MG, MG, NV, '', '', '', '', '', '', ''],
        ['', '', '', '', NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, '', '', '', '', '', ''],
        ['', '', '', '', NV, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, NV, '', '', '', '', '', ''],
        ['', '', '', NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, NV, '', '', '', '', '', ''],
        ['', '', NV, NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, NV, NV, NV, '', '', '', ''],
        ['', '', NV, MG, MG, NV, MG, MG, MG, MG, MG, MG, NV, MG, MG, NV, '', '', '', '', '', ''],
        ['', '', NV, NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, NV, '', '', '', '', '', ''],
        ['', NV, NV, MG, MG, NV, MG, MG, MG, MG, MG, MG, NV, MG, MG, NV, NV, '', '', '', '', ''],
        ['', NV, NV, NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, NV, NV, NV, '', '', '', ''],
        ['', NV, NV, MG, NV, NV, MG, MG, MG, MG, MG, MG, NV, NV, MG, NV, NV, '', '', '', '', ''],
        ['', NV, NV, NV, NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, NV, NV, NV, NV, '', '', '', ''],
        ['', NV, NV, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, NV, NV, '', '', ''],
        ['', DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 14,
      height: 10,
      anchorX: 7,
      anchorY: 9,
      lines: [
        "    .----.    ",
        "   .|====|.   ",
        "  | |[::]| |  ",
        " .|=|====|=|. ",
        " |  |[::]|  | ",
        " |=||====||=| ",
        " |  |[::]|  | ",
        " |==[====]==| ",
        " |__|____|__| ",
        "::..::..::..::",
      ],
      colors: [
        ['', '', '', '', NV, NV, NV, NV, NV, NV, '', '', '', ''],
        ['', '', '', NV, MG, MG, MG, MG, MG, MG, NV, '', '', ''],
        ['', '', NV, NV, CY, CY, CY, CY, NV, NV, '', '', '', ''],
        ['', NV, NV, MG, MG, MG, MG, MG, MG, NV, NV, '', '', ''],
        ['', NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, '', '', ''],
        ['', NV, MG, MG, MG, MG, MG, MG, MG, MG, MG, NV, '', ''],
        ['', NV, NV, CY, CY, CY, CY, CY, CY, NV, NV, '', '', ''],
        ['', NV, MG, MG, MG, MG, MG, MG, MG, MG, MG, NV, '', ''],
        ['', DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, DK, '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 8,
      height: 6,
      anchorX: 4,
      anchorY: 5,
      lines: [
        "  .--.  ",
        " .|==|. ",
        "| |::| |",
        "|=|==|=|",
        "| |::| |",
        "::..::..",
      ],
      colors: [
        ['', '', NV, NV, NV, NV, '', ''],
        ['', NV, MG, MG, MG, MG, NV, ''],
        [NV, NV, CY, CY, CY, CY, NV, NV],
        [NV, MG, MG, MG, MG, MG, MG, NV],
        [NV, NV, CY, CY, CY, CY, NV, NV],
        [BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 4,
      height: 3,
      anchorX: 2,
      anchorY: 2,
      lines: [
        ".--.",
        "|::|",
        "::..",
      ],
      colors: [
        [NV, MG, MG, NV],
        [NV, CY, CY, NV],
        [BS, BS, BS, BS],
      ],
    },
  },
};
