import { SpriteDefinition } from '../../ascii/types';

const CY = '#06b6d4'; // Cyan Pulse Corona
const MG = '#ec4899'; // Magenta Accent Trim
const GD = '#fde047'; // Gold Needle Antenna
const NV = '#090d16'; // Deep Midnight Body
const DK = '#1e1b4b'; // Shadow Crevice
const BS = '#020617'; // Cyber Grid Foundation

export const CyberSpireSprite: SpriteDefinition = {
  id: 'scenery_cyber_spire',
  name: 'Cyber Needle Spire',
  category: 'BUILDING',
  defaultColor: '#ec4899',
  worldWidth: 180,
  worldHeight: 460,
  visualScale: 1.1,
  variants: {
    close: {
      width: 18,
      height: 18,
      anchorX: 9,
      anchorY: 17,
      lines: [
        "        ||        ",
        "        ||        ",
        "       (☼☼)       ",
        "       /||\\       ",
        "      (====)      ",
        "      /|::|\\      ",
        "     (======)     ",
        "     /|####|\\     ",
        "    (========)    ",
        "    /|::::::|\\    ",
        "   (==========)   ",
        "   /|########|\\   ",
        "  (============)  ",
        "  /|::::::::::|\\  ",
        " (==============) ",
        " |##############| ",
        " |==============| ",
        "::..::..::..::..::",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', GD, GD, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', GD, GD, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', GD, GD, GD, GD, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', CY, CY, CY, CY, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', MG, MG, MG, MG, MG, MG, '', '', '', '', '', ''],
        ['', '', '', '', '', '', CY, NV, CY, CY, NV, CY, '', '', '', '', '', ''],
        ['', '', '', '', '', MG, MG, MG, MG, MG, MG, MG, MG, '', '', '', '', ''],
        ['', '', '', '', '', CY, NV, MG, MG, MG, MG, NV, CY, '', '', '', '', ''],
        ['', '', '', '', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, '', '', '', ''],
        ['', '', '', '', CY, NV, CY, CY, DK, DK, CY, CY, NV, CY, '', '', '', ''],
        ['', '', '', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, '', '', ''],
        ['', '', '', CY, NV, MG, MG, MG, MG, MG, MG, MG, MG, NV, CY, '', '', ''],
        ['', '', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, '', ''],
        ['', '', CY, NV, CY, CY, CY, DK, DK, DK, DK, CY, CY, CY, NV, CY, '', ''],
        ['', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, ''],
        ['', NV, NV, CY, CY, MG, MG, MG, MG, MG, MG, MG, MG, CY, CY, NV, NV, ''],
        ['', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 12,
      height: 12,
      anchorX: 6,
      anchorY: 11,
      lines: [
        "     ||     ",
        "    (☼☼)    ",
        "    /||\\    ",
        "   (====)   ",
        "   /|::|\\   ",
        "  (======)  ",
        "  /|####|\\  ",
        " (========) ",
        " /|::::::|\\ ",
        "(==========)",
        "|##########|",
        "::..::..::..",
      ],
      colors: [
        ['', '', '', '', '', GD, GD, '', '', '', '', ''],
        ['', '', '', '', GD, GD, GD, GD, '', '', '', ''],
        ['', '', '', '', CY, CY, CY, CY, '', '', '', ''],
        ['', '', '', MG, MG, MG, MG, MG, MG, '', '', ''],
        ['', '', '', CY, NV, CY, CY, NV, CY, '', '', ''],
        ['', '', MG, MG, MG, MG, MG, MG, MG, MG, '', ''],
        ['', '', CY, NV, MG, MG, MG, MG, NV, CY, '', ''],
        ['', MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, ''],
        ['', CY, NV, CY, CY, DK, DK, CY, CY, NV, CY, ''],
        [MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG],
        [NV, NV, CY, CY, MG, MG, MG, MG, CY, CY, NV, NV],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 8,
      height: 7,
      anchorX: 4,
      anchorY: 6,
      lines: [
        "   ||   ",
        "  (☼☼)  ",
        "  /||\\  ",
        " (====) ",
        " /|##|\\ ",
        "(======)",
        "::..::..",
      ],
      colors: [
        ['', '', '', GD, GD, '', '', ''],
        ['', '', GD, GD, GD, GD, '', ''],
        ['', '', CY, CY, CY, CY, '', ''],
        ['', MG, MG, MG, MG, MG, MG, ''],
        ['', CY, NV, MG, MG, NV, CY, ''],
        [MG, MG, MG, MG, MG, MG, MG, MG],
        [BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 4,
      height: 4,
      anchorX: 2,
      anchorY: 3,
      lines: [
        " || ",
        "(☼☼)",
        "/##\\",
        "::..",
      ],
      colors: [
        ['', GD, GD, ''],
        [GD, GD, GD, GD],
        [CY, MG, MG, CY],
        [BS, BS, BS, BS],
      ],
    },
  },
};
