import { SpriteDefinition } from '../../ascii/types';

const TR = '#78350f'; // Weathered Dried Wood
const DK = '#451a03'; // Deep Branch Shadow
const CH = '#292524'; // Charred Charcoal Split
const BS = '#d97706'; // Desert Arid Ground

export const DeadTreeSprite: SpriteDefinition = {
  id: 'scenery_dead_tree',
  name: 'Gnarled Desert Dead Tree',
  category: 'VEGETATION',
  defaultColor: '#78350f',
  worldWidth: 100,
  worldHeight: 140,
  visualScale: 1.0,
  variants: {
    close: {
      width: 18,
      height: 14,
      anchorX: 9,
      anchorY: 13,
      lines: [
        " \\  /       / /   ",
        "  \\/ /\\   _/_/    ",
        "   \\/  \\ / _/     ",
        "    \\  _\\//       ",
        "  _  \\/  /   _    ",
        " / \\_/  /\\  / \\   ",
        " \\_   _/  \\/ _/   ",
        "   \\_/  _  \\/     ",
        "     | | \\_/      ",
        "     | |  |       ",
        "     | |  |       ",
        "    /| | / \\      ",
        "  _/ | |/   \\_    ",
        "::..::..::..::..::",
      ],
      colors: [
        [TR, '', TR, '', '', '', '', '', TR, '', TR, '', '', '', '', '', '', ''],
        ['', TR, TR, '', TR, TR, '', '', DK, DK, DK, '', '', '', '', '', '', ''],
        ['', '', TR, TR, '', '', TR, '', TR, '', DK, DK, '', '', '', '', '', ''],
        ['', '', '', TR, '', DK, TR, TR, TR, '', '', '', '', '', '', '', '', ''],
        ['', TR, '', '', TR, TR, '', '', TR, '', '', '', TR, '', '', '', '', ''],
        [TR, '', TR, TR, '', '', TR, TR, '', TR, '', TR, '', TR, '', '', '', ''],
        ['', TR, '', '', '', TR, TR, '', '', TR, TR, '', DK, '', '', '', '', ''],
        ['', '', TR, TR, TR, '', '', TR, '', '', TR, TR, '', '', '', '', '', ''],
        ['', '', '', '', '', TR, TR, '', TR, TR, TR, '', '', '', '', '', '', ''],
        ['', '', '', '', '', TR, TR, '', '', TR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', TR, CH, '', '', TR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', TR, TR, CH, '', TR, '', TR, '', '', '', '', '', '', ''],
        ['', '', TR, TR, '', TR, CH, TR, '', '', '', TR, TR, '', '', '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 12,
      height: 10,
      anchorX: 6,
      anchorY: 9,
      lines: [
        "\\  /   / /  ",
        " \\/ \\_/_/   ",
        "  \\_// /    ",
        " _ \\/ / _   ",
        "/ \\_\\/ / \\  ",
        "\\_  _\\/_/   ",
        "  \\/ | |    ",
        "   | | |    ",
        "  /| |/ \\   ",
        "::..::..::..",
      ],
      colors: [
        [TR, '', TR, '', '', '', TR, '', TR, '', '', ''],
        ['', TR, TR, '', TR, TR, DK, DK, '', '', '', ''],
        ['', '', TR, TR, TR, '', TR, '', '', '', '', ''],
        ['', TR, '', TR, TR, '', TR, '', TR, '', '', ''],
        [TR, '', TR, TR, TR, TR, '', TR, '', TR, '', ''],
        ['', TR, '', '', TR, TR, TR, DK, '', '', '', ''],
        ['', '', TR, TR, '', TR, TR, '', '', '', '', ''],
        ['', '', '', TR, '', TR, TR, '', '', '', '', ''],
        ['', '', TR, TR, '', TR, TR, '', TR, '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 8,
      height: 6,
      anchorX: 4,
      anchorY: 5,
      lines: [
        "\\/  /\\  ",
        " \\_//   ",
        " _\\/ _  ",
        " \\/\\/_  ",
        "  |||   ",
        "::..::..",
      ],
      colors: [
        [TR, TR, '', '', TR, TR, '', ''],
        ['', TR, TR, TR, TR, '', '', ''],
        ['', TR, TR, TR, '', TR, '', ''],
        ['', TR, TR, TR, TR, DK, '', ''],
        ['', '', TR, TR, TR, '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 4,
      height: 3,
      anchorX: 2,
      anchorY: 2,
      lines: [
        "\\// ",
        " || ",
        "::..",
      ],
      colors: [
        [TR, TR, TR, ''],
        ['', TR, TR, ''],
        [BS, BS, BS, BS],
      ],
    },
  },
};
