import { SpriteDefinition } from '../../ascii/types';

const SN = '#ffffff'; // Alpine Powder Snow
const IC = '#93c5fd'; // Cyan Frost Highlight
const ND = '#064e3b'; // Dark Spruce Needles
const BR = '#78350f'; // Timber Trunk
const BS = '#cbd5e1'; // Permafrost Snow Base

export const DenseSnowPineSprite: SpriteDefinition = {
  id: 'scenery_dense_snow_pine',
  name: 'Dense Snow-Laden Conifer',
  category: 'VEGETATION',
  defaultColor: '#ffffff',
  worldWidth: 160,
  worldHeight: 280,
  visualScale: 1.05,
  variants: {
    close: {
      width: 20,
      height: 16,
      anchorX: 10,
      anchorY: 15,
      lines: [
        "        .---.       ",
        "       /░░░░░\\      ",
        "      /=======/     ",
        "     .*░░░░░░░*.    ",
        "    /===========/   ",
        "   .*░░░░░░░░░░░*.  ",
        "  /===============/ ",
        " .*░░░░░░░░░░░░░░░*.",
        "/==================/",
        "\\_//\\//\\//\\//\\//\\_/ ",
        "        |▒▒|        ",
        "        |▒▒|        ",
        "        |▒▒|        ",
        "       _|▒▒|_       ",
        "      /======\\      ",
        "    ::..::..::..    ",
      ],
      colors: [
        ['', '', '', '', '', '', '', SN, SN, SN, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', SN, SN, SN, SN, SN, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', IC, IC, IC, IC, IC, IC, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', SN, SN, SN, SN, SN, SN, SN, SN, '', '', '', '', '', '', '', ''],
        ['', '', '', IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, '', '', '', '', '', '', ''],
        ['', '', SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, '', '', '', '', '', ''],
        ['', IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, '', '', '', '', ''],
        ['', SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, '', ''],
        [IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, ''],
        [ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ''],
        ['', '', '', '', '', '', '', '', BR, BR, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, BR, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, BR, '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', BR, BR, BR, BR, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', BS, BS, BS, BS, BS, BS, '', '', '', '', '', '', '', ''],
        ['', '', '', '', BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, '', '', '', '', '', ''],
      ],
    },
    near: {
      width: 14,
      height: 11,
      anchorX: 7,
      anchorY: 10,
      lines: [
        "     .---.    ",
        "    /░░░░░\\   ",
        "   .*░░░░░░*. ",
        "  /==========/",
        " .*░░░░░░░░░*.",
        "/============/",
        "\\_//\\//\\//\\_/ ",
        "     |▒▒|     ",
        "     |▒▒|     ",
        "    /====\\    ",
        "  ::..::..::  ",
      ],
      colors: [
        ['', '', '', '', '', SN, SN, SN, '', '', '', '', '', ''],
        ['', '', '', '', SN, SN, SN, SN, SN, '', '', '', '', ''],
        ['', '', '', SN, SN, SN, SN, SN, SN, SN, '', '', '', ''],
        ['', '', IC, IC, IC, IC, IC, IC, IC, IC, IC, '', '', ''],
        ['', SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, SN, '', ''],
        [IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, IC, ''],
        [ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ''],
        ['', '', '', '', '', BR, BR, '', '', '', '', '', '', ''],
        ['', '', '', '', '', BR, BR, '', '', '', '', '', '', ''],
        ['', '', '', '', BS, BS, BS, BS, '', '', '', '', '', ''],
        ['', '', BS, BS, BS, BS, BS, BS, BS, BS, '', '', '', ''],
      ],
    },
    medium: {
      width: 8,
      height: 6,
      anchorX: 4,
      anchorY: 5,
      lines: [
        "  .---. ",
        " .*░░░*.",
        "/======/",
        " \\_//\\_/",
        "  |▒▒|  ",
        " ::..:: ",
      ],
      colors: [
        ['', '', SN, SN, SN, '', '', ''],
        ['', SN, SN, SN, SN, SN, '', ''],
        [IC, IC, IC, IC, IC, IC, IC, IC],
        ['', ND, ND, ND, ND, ND, '', ''],
        ['', '', BR, BR, '', '', '', ''],
        ['', BS, BS, BS, BS, BS, '', ''],
      ],
    },
    far: {
      width: 4,
      height: 3,
      anchorX: 2,
      anchorY: 2,
      lines: [
        ".--.",
        "|**|",
        "::..",
      ],
      colors: [
        [SN, SN, SN, SN],
        [IC, ND, ND, IC],
        [BS, BS, BS, BS],
      ],
    },
  },
};
