import { SpriteDefinition } from '../../ascii/types';

const LM = '#84cc16'; // Spiky Desert Yucca Lime Crown
const OL = '#4d7c0f'; // Olive Shade Leaves
const TR = '#78350f'; // Fibrous Desert Bark
const DK = '#451a03'; // Trunk Shadow
const BS = '#d97706'; // Desert Arid Earth

export const JoshuaTreeSprite: SpriteDefinition = {
  id: 'scenery_joshua_tree',
  name: 'Desert Joshua Tree',
  category: 'VEGETATION',
  defaultColor: '#84cc16',
  worldWidth: 110,
  worldHeight: 150,
  visualScale: 1.0,
  variants: {
    close: {
      width: 18,
      height: 14,
      anchorX: 9,
      anchorY: 13,
      lines: [
        " <**>        <**> ",
        "  \\|/  <**>  \\|/  ",
        "   |   \\|/    |   ",
        "   |    |     |   ",
        "   |   /     /    ",
        "   \\__/__   /     ",
        "      \\  \\_/      ",
        "       \\_  /      ",
        "        | |       ",
        "        | |       ",
        "        | |       ",
        "       /| |\\      ",
        "     _/ | | \\_    ",
        "::..::..::..::..::",
      ],
      colors: [
        ['', LM, LM, LM, '', '', '', '', '', '', '', LM, LM, LM, '', '', '', ''],
        ['', '', OL, OL, '', '', LM, LM, LM, '', '', OL, OL, '', '', '', '', ''],
        ['', '', '', TR, '', '', OL, OL, '', '', '', '', TR, '', '', '', '', ''],
        ['', '', '', TR, '', '', '', TR, '', '', '', '', TR, '', '', '', '', ''],
        ['', '', '', TR, '', '', TR, '', '', '', '', TR, '', '', '', '', '', ''],
        ['', '', '', TR, TR, TR, TR, '', '', '', TR, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', TR, '', TR, TR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', TR, TR, '', TR, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', TR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', TR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', TR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', TR, TR, DK, TR, '', '', '', '', '', '', ''],
        ['', '', '', '', '', TR, TR, '', TR, DK, '', TR, TR, '', '', '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    near: {
      width: 12,
      height: 10,
      anchorX: 6,
      anchorY: 9,
      lines: [
        "<*>     <*> ",
        "\\|/ <*> \\|/ ",
        " |  \\|/  |  ",
        " |   |  /   ",
        " \\__/ _/    ",
        "   \\_/      ",
        "   | |      ",
        "   | |      ",
        "  /| |\\     ",
        "::..::..::..",
      ],
      colors: [
        [LM, LM, LM, '', '', '', '', '', LM, LM, LM, ''],
        [OL, OL, OL, '', LM, LM, LM, '', OL, OL, OL, ''],
        ['', TR, '', '', OL, OL, OL, '', '', TR, '', ''],
        ['', TR, '', '', '', TR, '', '', TR, '', '', ''],
        ['', TR, TR, TR, '', TR, TR, '', '', '', '', ''],
        ['', '', '', TR, TR, '', '', '', '', '', '', ''],
        ['', '', '', TR, DK, '', '', '', '', '', '', ''],
        ['', '', '', TR, DK, '', '', '', '', '', '', ''],
        ['', '', TR, TR, DK, TR, '', '', '', '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    medium: {
      width: 8,
      height: 6,
      anchorX: 4,
      anchorY: 5,
      lines: [
        "*   * * ",
        "\\|/ \\|/ ",
        " \\_//   ",
        "  | |   ",
        " /| |\\  ",
        "::..::..",
      ],
      colors: [
        [LM, '', '', LM, '', LM, '', ''],
        [OL, OL, OL, '', OL, OL, OL, ''],
        ['', TR, TR, TR, TR, '', '', ''],
        ['', '', TR, DK, '', '', '', ''],
        ['', TR, TR, DK, TR, '', '', ''],
        [BS, BS, BS, BS, BS, BS, BS, BS],
      ],
    },
    far: {
      width: 4,
      height: 3,
      anchorX: 2,
      anchorY: 2,
      lines: [
        "*** ",
        " |  ",
        "::..",
      ],
      colors: [
        [LM, LM, LM, ''],
        ['', TR, '', ''],
        [BS, BS, BS, BS],
      ],
    },
  },
};
