import { SpriteDefinition } from '../../ascii/types';

const GL = '#fde047'; // Golden Beacon Glow
const BL = '#38bdf8'; // Lantern Glass
const RD = '#ef4444'; // Red Tower Stripes
const WT = '#f8fafc'; // White Granite Tower
const DK = '#1e293b'; // Balcony Railing / Roof
const RK = '#475569'; // Base Rock Platform

export const LighthouseSprite: SpriteDefinition = {
  id: 'lighthouse',
  name: 'Coastal Lighthouse',
  category: 'LANDMARK',
  defaultColor: '#ef4444',
  worldWidth: 160,
  worldHeight: 420,
  visualScale: 1.1,
  variants: {
    close: {
      width: 19,
      height: 22,
      anchorX: 9,
      anchorY: 21,
      lines: [
        "        /\\         ",
        "       /  \\        ",
        "      /____\\       ",
        "      |*GL*|       ",
        "     [======]      ",
        "      |    |       ",
        "      | RD |       ",
        "      |====|       ",
        "     /      \\      ",
        "    /   WT   \\     ",
        "    |========|     ",
        "    |   RD   |     ",
        "    |========|     ",
        "   /    WT    \\    ",
        "  /   [====]   \\   ",
        "  |     RD     |   ",
        "  |============|   ",
        " /      WT      \\  ",
        "/      (==)      \\ ",
        "|________________| ",
        "  /============\\   ",
        " /==============\\  ",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', DK, DK, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', DK, DK, DK, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', DK, DK, DK, DK, DK, DK, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', BL, GL, GL, GL, GL, BL, '', '', '', '', '', '', ''],
        ['', '', '', '', '', DK, DK, DK, DK, DK, DK, DK, DK, '', '', '', '', '', ''],
        ['', '', '', '', '', '', RD, RD, RD, RD, RD, RD, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', RD, RD, RD, RD, RD, RD, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', RD, RD, RD, RD, RD, RD, '', '', '', '', '', '', ''],
        ['', '', '', '', '', WT, WT, WT, WT, WT, WT, WT, WT, '', '', '', '', '', ''],
        ['', '', '', '', WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, '', '', '', '', ''],
        ['', '', '', '', WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, '', '', '', '', ''],
        ['', '', '', '', RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, '', '', '', '', ''],
        ['', '', '', '', RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, '', '', '', '', ''],
        ['', '', '', WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, '', '', '', ''],
        ['', '', WT, WT, WT, DK, DK, DK, DK, DK, DK, WT, WT, WT, WT, WT, '', '', ''],
        ['', '', RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, '', '', ''],
        ['', '', RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, '', '', ''],
        ['', WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, '', ''],
        [WT, WT, WT, WT, WT, WT, DK, DK, DK, DK, WT, WT, WT, WT, WT, WT, WT, WT, ''],
        [RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, ''],
        ['', '', RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, '', '', ''],
        ['', RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, '', ''],
      ],
    },
    near: {
      width: 13,
      height: 15,
      anchorX: 6,
      anchorY: 14,
      lines: [
        "     /\\      ",
        "    /  \\     ",
        "    |*GL*|   ",
        "   [====]    ",
        "    |RD|     ",
        "    |==|     ",
        "   / WT \\    ",
        "   |====|    ",
        "   | RD |    ",
        "   |====|    ",
        "  /  WT  \\   ",
        "  |  RD  |   ",
        " /   WT   \\  ",
        "|__________| ",
        "/==========\\ ",
      ],
      colors: [
        ['', '', '', '', '', DK, DK, '', '', '', '', '', ''],
        ['', '', '', '', DK, DK, DK, DK, '', '', '', '', ''],
        ['', '', '', '', BL, GL, GL, BL, '', '', '', '', ''],
        ['', '', '', DK, DK, DK, DK, DK, DK, '', '', '', ''],
        ['', '', '', '', RD, RD, RD, RD, '', '', '', '', ''],
        ['', '', '', '', RD, RD, RD, RD, '', '', '', '', ''],
        ['', '', '', WT, WT, WT, WT, WT, WT, '', '', '', ''],
        ['', '', '', WT, WT, WT, WT, WT, WT, '', '', '', ''],
        ['', '', '', RD, RD, RD, RD, RD, RD, '', '', '', ''],
        ['', '', '', RD, RD, RD, RD, RD, RD, '', '', '', ''],
        ['', '', WT, WT, WT, WT, WT, WT, WT, WT, '', '', ''],
        ['', '', RD, RD, RD, RD, RD, RD, RD, RD, '', '', ''],
        ['', WT, WT, WT, WT, WT, WT, WT, WT, WT, WT, '', ''],
        [RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, ''],
        [RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, RK, ''],
      ],
    },
    medium: {
      width: 9,
      height: 9,
      anchorX: 4,
      anchorY: 8,
      lines: [
        "   /\\    ",
        "  |*GL*| ",
        "  [====] ",
        "   |RD|  ",
        "  / WT \\ ",
        "  | RD | ",
        " /  WT  \\",
        "|_______|",
        "/=======\\",
      ],
      colors: [
        ['', '', '', DK, DK, '', '', '', ''],
        ['', '', BL, GL, GL, BL, '', '', ''],
        ['', '', DK, DK, DK, DK, DK, DK, ''],
        ['', '', '', RD, RD, RD, '', '', ''],
        ['', '', WT, WT, WT, WT, WT, '', ''],
        ['', '', RD, RD, RD, RD, RD, '', ''],
        ['', WT, WT, WT, WT, WT, WT, WT, ''],
        [RK, RK, RK, RK, RK, RK, RK, RK, RK],
        [RK, RK, RK, RK, RK, RK, RK, RK, RK],
      ],
    },
    far: {
      width: 5,
      height: 5,
      anchorX: 2,
      anchorY: 4,
      lines: [
        "  ^  ",
        " |*| ",
        " |R| ",
        " |W| ",
        "|___|",
      ],
      colors: [
        ['', '', DK, '', ''],
        ['', BL, GL, BL, ''],
        ['', RD, RD, RD, ''],
        ['', WT, WT, WT, ''],
        [RK, RK, RK, RK, RK],
      ],
    },
  },
};
