import { SpriteDefinition } from '../../ascii/types';

const SN = '#ffffff'; // Sunlit Powder Snow Mantle
const SI = '#e2e8f0'; // Snow Shadow / Soft Ice
const IB = '#93c5fd'; // Glacial Ice Cyan Accent
const DG = '#064e3b'; // Deep Spruce Pine Needles (Underneath)
const BR = '#78350f'; // Frozen Bark Trunk
const BS = '#cbd5e1'; // Snow Ground Contact

export const SnowPineSprite: SpriteDefinition = {
  id: 'snow_pine',
  name: 'Glacial Snow Pine',
  category: 'VEGETATION_LARGE',
  defaultColor: '#f8fafc',
  worldWidth: 150,
  worldHeight: 210,
  visualScale: 1.0,
  variants: {
    close: {
      width: 19,
      height: 18,
      anchorX: 9,
      anchorY: 17,
      lines: [
        "        *.*        ",
        "       /░*░\\       ",
        "      /░***░\\      ",
        "      *░░░░░*      ",
        "     /░░***░░\\     ",
        "    /░░*****░░\\    ",
        "    *░░░░░░░░░*    ",
        "   /░░*******░░\\   ",
        "  /░░*********░░\\  ",
        "  *░░░░░░░░░░░░░*  ",
        " /░░***********░░\\ ",
        "/░░*************░░\\",
        "*░░░░░░░░░░░░░░░░░*",
        "       |▓▓▓|       ",
        "       |▓▓▓|       ",
        "       |▓▓▓|       ",
        "      /▓▓▓▓▓\\      ",
        "   ..*░░░░░░░*..   ",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', SN, SN, SN, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', SN, SI, DG, SI, SN, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', SN, SI, DG, DG, DG, SI, SN, '', '', '', '', '', ''],
        ['', '', '', '', '', '', SN, SI, IB, IB, IB, SI, SN, '', '', '', '', '', ''],
        ['', '', '', '', '', SN, SI, DG, DG, DG, DG, DG, SI, SN, '', '', '', '', ''],
        ['', '', '', '', SN, SI, DG, DG, DG, DG, DG, DG, DG, SI, SN, '', '', '', ''],
        ['', '', '', '', SN, SI, IB, IB, IB, IB, IB, IB, IB, SI, SN, '', '', '', ''],
        ['', '', '', SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN, '', '', ''],
        ['', '', SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN, '', ''],
        ['', '', SN, SI, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, SI, SN, '', ''],
        ['', SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN, ''],
        [SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN],
        [SN, SI, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, SI, SN],
        ['', '', '', '', '', '', '', BR, BR, BR, BR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', BR, BR, BR, BR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', BR, BR, BR, BR, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', BR, BR, BR, BR, BR, BR, '', '', '', '', '', '', ''],
        ['', '', '', BS, BS, SN, SI, SI, SI, SI, SI, SI, SN, BS, BS, '', '', '', ''],
      ],
    },
    near: {
      width: 14,
      height: 12,
      anchorX: 7,
      anchorY: 11,
      lines: [
        "      **      ",
        "     /░░\\     ",
        "    *░░░░*    ",
        "   /░░**░░\\   ",
        "  *░░░░░░░░*  ",
        " /░░******░░\\ ",
        "*░░░░░░░░░░░░*",
        "/░░********░░\\",
        "**░░░░░░░░░░**",
        "     |▓▓|     ",
        "     |▓▓|     ",
        "   .*░░░░*.   ",
      ],
      colors: [
        ['', '', '', '', '', '', SN, SN, '', '', '', '', '', ''],
        ['', '', '', '', '', SN, SI, SI, SN, '', '', '', '', ''],
        ['', '', '', '', SN, SI, DG, DG, SI, SN, '', '', '', ''],
        ['', '', '', SN, SI, DG, DG, DG, DG, SI, SN, '', '', ''],
        ['', '', SN, SI, IB, IB, IB, IB, IB, IB, SI, SN, '', ''],
        ['', SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN, ''],
        [SN, SI, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, SI, SN],
        [SN, SI, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, SI, SN],
        [SN, SI, IB, IB, IB, IB, IB, IB, IB, IB, IB, IB, SI, SN],
        ['', '', '', '', '', BR, BR, BR, BR, '', '', '', '', ''],
        ['', '', '', '', '', BR, BR, BR, BR, '', '', '', '', ''],
        ['', '', '', BS, SN, SI, SI, SI, SI, SN, BS, '', '', ''],
      ],
    },
    medium: {
      width: 10,
      height: 7,
      anchorX: 5,
      anchorY: 6,
      lines: [
        "    **    ",
        "   /░░\\   ",
        "  /░**░\\  ",
        " *░░░░░░* ",
        "/░░****░░\\",
        "   |▓▓|   ",
        "  .*░░*.  ",
      ],
      colors: [
        ['', '', '', '', SN, SN, '', '', '', ''],
        ['', '', '', SN, SI, SI, SN, '', '', ''],
        ['', '', SN, SI, DG, DG, SI, SN, '', ''],
        ['', SN, SI, IB, IB, IB, IB, SI, SN, ''],
        [SN, SI, DG, DG, DG, DG, DG, DG, SI, SN],
        ['', '', '', BR, BR, BR, BR, '', '', ''],
        ['', '', BS, SN, SI, SI, SN, BS, '', ''],
      ],
    },
    far: {
      width: 6,
      height: 4,
      anchorX: 3,
      anchorY: 3,
      lines: [
        "  **  ",
        " /░░\\ ",
        "*░░░░*",
        "  ||  ",
      ],
      colors: [
        ['', '', SN, SN, '', ''],
        ['', SN, SI, SI, SN, ''],
        [SN, SI, DG, DG, SI, SN],
        ['', '', BR, BR, '', ''],
      ],
    },
  },
};
