import { SpriteDefinition } from '../../ascii/types';

const ND = '#065f46'; // Deep Spruce Needle Green
const NL = '#10b981'; // Sunlit Pine Needle Highlight
const BR = '#78350f'; // Tall Slender Trunk Bark
const DK = '#451a03'; // Trunk Shadow
const BS = '#064e3b'; // Forest Floor Contact

export const TallPineSprite: SpriteDefinition = {
  id: 'scenery_tall_pine',
  name: 'Towering Lodgepole Pine',
  category: 'VEGETATION',
  defaultColor: '#065f46',
  worldWidth: 120,
  worldHeight: 340,
  visualScale: 1.1,
  variants: {
    close: {
      width: 18,
      height: 18,
      anchorX: 9,
      anchorY: 17,
      lines: [
        "        /\\        ",
        "       /░░\\       ",
        "      /▒▒▒▒\\      ",
        "     /▓▓▓▓▓▓\\     ",
        "    /░░░░░░░░\\    ",
        "   /▒▒▒▒▒▒▒▒▒▒\\   ",
        "  /▓▓▓▓▓▓▓▓▓▓▓▓\\  ",
        "  \\_//\\//\\//\\_/   ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "        ||        ",
        "       _||_       ",
        "     ::..::..     ",
      ],
      colors: [
        ['', '', '', '', '', '', '', '', NL, NL, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', NL, ND, ND, NL, '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', NL, ND, ND, ND, ND, NL, '', '', '', '', '', ''],
        ['', '', '', '', '', NL, ND, ND, ND, ND, ND, ND, NL, '', '', '', '', ''],
        ['', '', '', '', NL, ND, ND, ND, ND, ND, ND, ND, ND, NL, '', '', '', ''],
        ['', '', '', NL, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, NL, '', '', ''],
        ['', '', NL, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, NL, '', ''],
        ['', '', NL, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, ND, NL, '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', BR, DK, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', BR, BR, DK, DK, '', '', '', '', '', '', ''],
        ['', '', '', '', '', BS, BS, BS, BS, BS, BS, BS, BS, '', '', '', '', ''],
      ],
    },
    near: {
      width: 12,
      height: 12,
      anchorX: 6,
      anchorY: 11,
      lines: [
        "     /\\     ",
        "    /░░\\    ",
        "   /▒▒▒▒\\   ",
        "  /▓▓▓▓▓▓\\  ",
        " /░░░░░░░░\\ ",
        " \\_//\\//\\_/ ",
        "     ||     ",
        "     ||     ",
        "     ||     ",
        "     ||     ",
        "    _||_    ",
        "  ::..::..  ",
      ],
      colors: [
        ['', '', '', '', '', NL, NL, '', '', '', '', ''],
        ['', '', '', '', NL, ND, ND, NL, '', '', '', ''],
        ['', '', '', NL, ND, ND, ND, ND, NL, '', '', ''],
        ['', '', NL, ND, ND, ND, ND, ND, ND, NL, '', ''],
        ['', NL, ND, ND, ND, ND, ND, ND, ND, ND, NL, ''],
        ['', NL, ND, ND, ND, ND, ND, ND, ND, ND, NL, ''],
        ['', '', '', '', '', BR, DK, '', '', '', '', ''],
        ['', '', '', '', '', BR, DK, '', '', '', '', ''],
        ['', '', '', '', '', BR, DK, '', '', '', '', ''],
        ['', '', '', '', '', BR, DK, '', '', '', '', ''],
        ['', '', '', '', BR, BR, DK, DK, '', '', '', ''],
        ['', '', BS, BS, BS, BS, BS, BS, BS, BS, '', ''],
      ],
    },
    medium: {
      width: 8,
      height: 7,
      anchorX: 4,
      anchorY: 6,
      lines: [
        "   /\\   ",
        "  /░░\\  ",
        " /▒▒▒▒\\ ",
        " \\_//\\_/",
        "   ||   ",
        "   ||   ",
        " ::..:: ",
      ],
      colors: [
        ['', '', '', NL, NL, '', '', ''],
        ['', '', NL, ND, ND, NL, '', ''],
        ['', NL, ND, ND, ND, ND, NL, ''],
        ['', NL, ND, ND, ND, ND, NL, ''],
        ['', '', '', BR, DK, '', '', ''],
        ['', '', '', BR, DK, '', '', ''],
        ['', BS, BS, BS, BS, BS, BS, ''],
      ],
    },
    far: {
      width: 4,
      height: 4,
      anchorX: 2,
      anchorY: 3,
      lines: [
        " /\\ ",
        "/▒▒\\",
        " || ",
        "::..",
      ],
      colors: [
        ['', NL, NL, ''],
        [NL, ND, ND, NL],
        ['', BR, DK, ''],
        [BS, BS, BS, BS],
      ],
    },
  },
};
